CREATE TABLE roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

INSERT INTO roles (name, created_at, updated_at)
VALUES
('ROLE_ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ROLE_CUSTOMER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);